import { ADD_NPC_SPELL, ADD_NPC_ACTION, ADD_NPC_LENDENDARY_ACTION, ADD_NPC_REACTION, ADD_NPC_TRAIT, REMOVE_NPC_ACTION, REMOVE_NPC_SPELL, REMOVE_NPC_LENDENDARY_ACTION, REMOVE_NPC_REACTION, REMOVE_NPC_TRAIT, SET_CONFIG, SET_MODE, SET_NPC_ALIGNMENT, SET_NPC_ARMOR_CLASS, SET_NPC_ARMOR_TYPE, SET_NPC_ATTRIBUTE, SET_NPC_CONDITION_IMMUNITY, SET_NPC_DAMAGE_IMMUNITY, SET_NPC_DAMAGE_RESISTANCE, SET_NPC_DAMAGE_VULNERABILITY, SET_NPC_FP, SET_NPC_HEALTH, SET_NPC_HEALTH_DIE_MODIFIER, SET_NPC_HEALTH_DIE_NUMBER, SET_NPC_HEALTH_DIE_TYPE, SET_NPC_SAVE_ROLL_MODIFIER, SET_NPC_KEYWORDS, SET_NPC_LANGUAGES, SET_NPC_NAME, SET_NPC_PASSIVE_PERCEPTION, SET_NPC_SENSES, SET_NPC_SIZE, SET_NPC_SPEEDS, SET_NPC_XP, UPDATE_NPC_ACTION, UPDATE_NPC_TRAIT, UPDATE_NPC_LENDENDARY_ACTION, UPDATE_NPC_REACTION, UPDATE_NPC_SPELL, SET_NPC_ACTION_IS_ATTACK, SET_NPC_LEGENDARY_ACTION_IS_ATTACK, SET_NPC_SPELL_IS_ATTACK, UPDATE_SPELL_ATTACK_DETAILS, UPDATE_ACTION_ATTACK_DETAILS, UPDATE_LEGENDARY_ACTION_ATTACK_DETAILS, SET_NPC_SKILL, ADD_SPELL_DAMAGE, ADD_ACTION_DAMAGE, ADD_LEGENDARY_ACTION_DAMAGE, REMOVE_SPELL_DAMAGE, REMOVE_ACTION_DAMAGE, REMOVE_LEGENDARY_ACTION_DAMAGE, UPDATE_SPELL_DAMAGE, UPDATE_ACTION_DAMAGE, UPDATE_LEGENDARY_ACTION_DAMAGE, SET_NPC_DESCRIPTION, ADD_NPC_IMAGE, REMOVE_NPC_IMAGE, UPDATE_NPC_IMAGE, SET_NPC} from "./actionTypes";

export const setConfig = val => ({ type: SET_CONFIG, payload: val });
export const setMode = val => ({ type: SET_MODE, payload: val });

export const setNPC = val => ({ type: SET_NPC, payload: val});
export const setNPCName = val => ({ type: SET_NPC_NAME, payload: val });
export const setNPCSize = val => ({ type: SET_NPC_SIZE, payload: val });
export const setNPCKeywords = val => ({ type: SET_NPC_KEYWORDS, payload: val });
export const setNPCAlignment = val => ({ type: SET_NPC_ALIGNMENT, payload: val });
export const setNPCArmorClass = val => ({ type: SET_NPC_ARMOR_CLASS, payload: val });
export const setNPCArmorType = val => ({ type: SET_NPC_ARMOR_TYPE, payload: val });
export const setNPCHealth = val => ({ type: SET_NPC_HEALTH, payload: val });
export const setNPCHealthDieNumber = val => ({ type: SET_NPC_HEALTH_DIE_NUMBER, payload: val });
export const setNPCHealthDieModifier = val => ({ type: SET_NPC_HEALTH_DIE_MODIFIER, payload: val });
export const setNPCHealthDieType = val => ({ type: SET_NPC_HEALTH_DIE_TYPE, payload: val });
export const setNPCSpeeds =  val => ({ type: SET_NPC_SPEEDS, payload: val });
export const setNPCAttribute = (val, id) => ({ type: SET_NPC_ATTRIBUTE, payload: {val, id} });
export const setNPCSkill = (val, id) => ({ type: SET_NPC_SKILL, payload: {val, id} });
export const setNPCSaveRollModifier = (val, id) => ({ type: SET_NPC_SAVE_ROLL_MODIFIER, payload: {val, id} });
export const setNPCDamageVulnerability =  val => ({ type: SET_NPC_DAMAGE_VULNERABILITY, payload: val });
export const setNPCDamageResistance =  val => ({ type: SET_NPC_DAMAGE_RESISTANCE, payload: val });
export const setNPCDamageImmunity =  val => ({ type: SET_NPC_DAMAGE_IMMUNITY, payload: val });
export const setNPCConditionImmunity =  val => ({ type: SET_NPC_CONDITION_IMMUNITY, payload: val });
export const setNPCSenses = val => ({ type: SET_NPC_SENSES, payload: val });
export const setNPCPassivePerception = val => ({ type: SET_NPC_PASSIVE_PERCEPTION, payload: val });
export const setNPCLanguages = val => ({ type: SET_NPC_LANGUAGES, payload: val });
export const setNPCFP = val => ({ type: SET_NPC_FP, payload: val });
export const setNPCXP= val => ({ type: SET_NPC_XP, payload: val });
export const addNPCTrait = val => ({ type: ADD_NPC_TRAIT, payload: val });
export const addNPCAction = val => ({ type: ADD_NPC_ACTION, payload: val });
export const addNPCReaction = val => ({ type: ADD_NPC_REACTION, payload: val });
export const addNPCLegendaryAction = val => ({ type: ADD_NPC_LENDENDARY_ACTION, payload: val });
export const addNPCSpell = val => ({ type: ADD_NPC_SPELL, payload: val });
export const removeNPCTrait = val => ({ type: REMOVE_NPC_TRAIT, payload: val });
export const removeNPCAction = val => ({ type: REMOVE_NPC_ACTION, payload: val });
export const removeNPCReaction = val => ({ type: REMOVE_NPC_REACTION, payload: val });
export const removeNPCLegendaryAction = val => ({ type: REMOVE_NPC_LENDENDARY_ACTION, payload: val });
export const removeNPCSpell = val => ({ type: REMOVE_NPC_SPELL, payload: val });
export const updateNPCTrait = (val, index, field) => ({ type: UPDATE_NPC_TRAIT, payload: {val, index, field} });
export const updateNPCAction = (val, index, field) => ({ type: UPDATE_NPC_ACTION, payload: {val, index, field} });
export const updateNPCReaction = (val, index, field) => ({ type: UPDATE_NPC_REACTION, payload: {val, index, field} });
export const updateNPCLegendaryAction = (val, index, field) => ({ type: UPDATE_NPC_LENDENDARY_ACTION, payload: {val, index, field} });
export const updateNPCSpell = (val, index, field) => ({ type: UPDATE_NPC_SPELL, payload: {val, index, field} });
export const setNPCActionIsAttack = (val, index) => ({ type: SET_NPC_ACTION_IS_ATTACK, payload: {val, index} });
export const setNPCLegendaryActionIsAttack = (val, index) => ({ type: SET_NPC_LEGENDARY_ACTION_IS_ATTACK, payload: {val, index} });
export const setNPCSpellIsAttack = (val, index) => ({ type: SET_NPC_SPELL_IS_ATTACK, payload: {val, index} });
export const updateNPCSpellAttackDetails = (val, index, field) => ({ type: UPDATE_SPELL_ATTACK_DETAILS, payload: {val, index, field} });
export const updateNPCActionAttackDetails = (val, index, field) => ({ type: UPDATE_ACTION_ATTACK_DETAILS, payload: {val, index, field} });
export const updateNPCLegendaryActionAttackDetails = (val, index, field) => ({ type: UPDATE_LEGENDARY_ACTION_ATTACK_DETAILS, payload: {val, index, field} });
export const addNPCSpellDamage = (val, index) => ({ type: ADD_SPELL_DAMAGE, payload: {val, index}});
export const addNPCActionDamage = (val, index) => ({ type: ADD_ACTION_DAMAGE, payload: {val, index}});
export const addNPCLegendaryActionDamage = (val, index) => ({ type: ADD_LEGENDARY_ACTION_DAMAGE, payload: {val, index}});
export const removeNPCSpellDamage = (val, index) => ({ type: REMOVE_SPELL_DAMAGE, payload: {val, index}});
export const removeNPCActionDamage = (val, index) => ({ type: REMOVE_ACTION_DAMAGE, payload: {val, index}});
export const removeNPCLegendaryActionDamage = (val, index) => ({ type: REMOVE_LEGENDARY_ACTION_DAMAGE, payload: {val, index}});
export const updateNPCSpellDamage = (val, index, damageIndex, field) => ({ type: UPDATE_SPELL_DAMAGE, payload: {val, index, damageIndex, field}});
export const updateNPCActionDamage = (val, index, damageIndex, field) => ({ type: UPDATE_ACTION_DAMAGE, payload: {val, index, damageIndex, field}});
export const updateNPCLegendaryActionDamage = (val, index, damageIndex, field) => ({ type: UPDATE_LEGENDARY_ACTION_DAMAGE, payload: {val, index, damageIndex, field}});
export const setNPCDescription = (val) => ({ type: SET_NPC_DESCRIPTION, payload: val});
export const addNPCImage = (val) => ({type: ADD_NPC_IMAGE, payload: val});
export const removeNPCImage = (val) => ({type: REMOVE_NPC_IMAGE, payload: val});
export const updateNPCImage = (val, index) => ({type: UPDATE_NPC_IMAGE, payload: {val, index}});

export function makeAction( dispatch, action ) { return ( payload, ...arg ) => dispatch(action(payload, ...arg)) } ;